language: node_js
node_js:
- '7.6.0'
cache:
  yarn: true
  - node_modules
install:
  - yarn install
script:
  - yarn test
  - yarn coverage
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: oliver_young@qq.com
  api_key:
    secure: GBK5/AVRuUxUNe/1o4C26o9Yucm9nYCQcBJkBKb3a5rdZBALFGrABdwSdju+zfrvLl2yTxvDNAkFN82cJ7XRodPY9OL//qanXYQ6aLu+nru6ZutnfQChLjE5/r95qBz0Clz0b0frrLSlvP3VTGl9nEAdLYKdoi1/q+LXfDRAjfWTW1gO1gPLsM4yzn4AVniTFGHjekp7IXU7OvsJ5IBu5wTuaSu/c4XHv9KNRHOALg+mGxB7vskobVYbdn5laqAoA89yqrLXipogfnVO0mYfCNb3X9DHbvA8q83ug36vWUQW2VNvqTOA0ofj0UZXfjC++C3GNXFCUx4FQnp9Uximj8sO+ImiB3Rm/FZCTnlRroLtUVZ/Thgf7V+8X4QmjqDFQj8sX6Jze05XzhVbPfBQR6LYpH0kYs7Nw4a9SF8OchXaci8SKJ1DNZ+o1jbsGbKK4iQP9qoOd+CRr12BrqGWIENyyTln3chKhj7VWhMJeIgNB8BXI/+oJgh0RMuLIbWPWcKQCSSWtAliKrZgrrn64tInxIC0j0oQOtjC2AjYrDAHPCU6CNbwW8Bn5cK0tUdQI/9ryA0rAcPf6Fvne2e2KMoE0aoqKalBQKbTyt4p6cRlE2GAUSXpDrff6rp27ZhFLIwlluGlXo+p+4zMxeTbKkerFUwlIX/5WUOs75zugG4=
  on:
    tags: true
    repo: epegzz/sass-vars-loader